export type TimezoneOption = {
  value: string
  label: string
}

// Comprehensive list of country / region timezones (IANA identifiers).
// Defaults to Asia/Manila. The SearchableSelect filters this list as you type.
export const TIMEZONES: TimezoneOption[] = [
  // Asia
  { value: 'Asia/Manila', label: 'Asia/Manila — Philippines' },
  { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur — Malaysia' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore — Singapore' },
  { value: 'Asia/Jakarta', label: 'Asia/Jakarta — Indonesia' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok — Thailand' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Asia/Ho_Chi_Minh — Vietnam' },
  { value: 'Asia/Phnom_Penh', label: 'Asia/Phnom_Penh — Cambodia' },
  { value: 'Asia/Vientiane', label: 'Asia/Vientiane — Laos' },
  { value: 'Asia/Yangon', label: 'Asia/Yangon — Myanmar' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata — India' },
  { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu — Nepal' },
  { value: 'Asia/Dhaka', label: 'Asia/Dhaka — Bangladesh' },
  { value: 'Asia/Colombo', label: 'Asia/Colombo — Sri Lanka' },
  { value: 'Asia/Karachi', label: 'Asia/Karachi — Pakistan' },
  { value: 'Asia/Kabul', label: 'Asia/Kabul — Afghanistan' },
  { value: 'Asia/Tashkent', label: 'Asia/Tashkent — Uzbekistan' },
  { value: 'Asia/Almaty', label: 'Asia/Almaty — Kazakhstan' },
  { value: 'Asia/Bishkek', label: 'Asia/Bishkek — Kyrgyzstan' },
  { value: 'Asia/Dushanbe', label: 'Asia/Dushanbe — Tajikistan' },
  { value: 'Asia/Ashgabat', label: 'Asia/Ashgabat — Turkmenistan' },
  { value: 'Asia/Tehran', label: 'Asia/Tehran — Iran' },
  { value: 'Asia/Baghdad', label: 'Asia/Baghdad — Iraq' },
  { value: 'Asia/Riyadh', label: 'Asia/Riyadh — Saudi Arabia' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai — United Arab Emirates' },
  { value: 'Asia/Qatar', label: 'Asia/Qatar — Qatar' },
  { value: 'Asia/Kuwait', label: 'Asia/Kuwait — Kuwait' },
  { value: 'Asia/Bahrain', label: 'Asia/Bahrain — Bahrain' },
  { value: 'Asia/Oman', label: 'Asia/Muscat — Oman' },
  { value: 'Asia/Yerevan', label: 'Asia/Yerevan — Armenia' },
  { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi — Georgia' },
  { value: 'Asia/Baku', label: 'Asia/Baku — Azerbaijan' },
  { value: 'Asia/Beirut', label: 'Asia/Beirut — Lebanon' },
  { value: 'Asia/Damascus', label: 'Asia/Damascus — Syria' },
  { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem — Israel' },
  { value: 'Asia/Amman', label: 'Asia/Amman — Jordan' },
  { value: 'Asia/Gaza', label: 'Asia/Gaza — Palestine' },
  { value: 'Asia/Nicosia', label: 'Asia/Nicosia — Cyprus' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai — China' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong — Hong Kong' },
  { value: 'Asia/Taipei', label: 'Asia/Taipei — Taiwan' },
  { value: 'Asia/Macau', label: 'Asia/Macau — Macau' },
  { value: 'Asia/Ulaanbaatar', label: 'Asia/Ulaanbaatar — Mongolia' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul — South Korea' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo — Japan' },
  { value: 'Asia/Pyongyang', label: 'Asia/Pyongyang — North Korea' },

  // Europe
  { value: 'Europe/London', label: 'Europe/London — United Kingdom' },
  { value: 'Europe/Dublin', label: 'Europe/Dublin — Ireland' },
  { value: 'Europe/Lisbon', label: 'Europe/Lisbon — Portugal' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid — Spain' },
  { value: 'Europe/Paris', label: 'Europe/Paris — France' },
  { value: 'Europe/Brussels', label: 'Europe/Brussels — Belgium' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam — Netherlands' },
  { value: 'Europe/Luxembourg', label: 'Europe/Luxembourg — Luxembourg' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin — Germany' },
  { value: 'Europe/Zurich', label: 'Europe/Zurich — Switzerland' },
  { value: 'Europe/Vienna', label: 'Europe/Vienna — Austria' },
  { value: 'Europe/Rome', label: 'Europe/Rome — Italy' },
  { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen — Denmark' },
  { value: 'Europe/Oslo', label: 'Europe/Oslo — Norway' },
  { value: 'Europe/Stockholm', label: 'Europe/Stockholm — Sweden' },
  { value: 'Europe/Helsinki', label: 'Europe/Helsinki — Finland' },
  { value: 'Europe/Warsaw', label: 'Europe/Warsaw — Poland' },
  { value: 'Europe/Prague', label: 'Europe/Prague — Czechia' },
  { value: 'Europe/Bratislava', label: 'Europe/Bratislava — Slovakia' },
  { value: 'Europe/Budapest', label: 'Europe/Budapest — Hungary' },
  { value: 'Europe/Ljubljana', label: 'Europe/Ljubljana — Slovenia' },
  { value: 'Europe/Zagreb', label: 'Europe/Zagreb — Croatia' },
  { value: 'Europe/Belgrade', label: 'Europe/Belgrade — Serbia' },
  { value: 'Europe/Sarajevo', label: 'Europe/Sarajevo — Bosnia & Herzegovina' },
  { value: 'Europe/Skopje', label: 'Europe/Skopje — North Macedonia' },
  { value: 'Europe/Podgorica', label: 'Europe/Podgorica — Montenegro' },
  { value: 'Europe/Bucharest', label: 'Europe/Bucharest — Romania' },
  { value: 'Europe/Sofia', label: 'Europe/Sofia — Bulgaria' },
  { value: 'Europe/Athens', label: 'Europe/Athens — Greece' },
  { value: 'Europe/Tirane', label: 'Europe/Tirane — Albania' },
  { value: 'Europe/Kiev', label: 'Europe/Kyiv — Ukraine' },
  { value: 'Europe/Chisinau', label: 'Europe/Chisinau — Moldova' },
  { value: 'Europe/Vilnius', label: 'Europe/Vilnius — Lithuania' },
  { value: 'Europe/Riga', label: 'Europe/Riga — Latvia' },
  { value: 'Europe/Tallinn', label: 'Europe/Tallinn — Estonia' },
  { value: 'Europe/Minsk', label: 'Europe/Minsk — Belarus' },
  { value: 'Europe/Istanbul', label: 'Europe/Istanbul — Turkey' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow — Russia' },

  // Africa
  { value: 'Africa/Cairo', label: 'Africa/Cairo — Egypt' },
  { value: 'Africa/Tripoli', label: 'Africa/Tripoli — Libya' },
  { value: 'Africa/Tunis', label: 'Africa/Tunis — Tunisia' },
  { value: 'Africa/Algiers', label: 'Africa/Algiers — Algeria' },
  { value: 'Africa/Casablanca', label: 'Africa/Casablanca — Morocco' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos — Nigeria' },
  { value: 'Africa/Accra', label: 'Africa/Accra — Ghana' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi — Kenya' },
  { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa — Ethiopia' },
  { value: 'Africa/Khartoum', label: 'Africa/Khartoum — Sudan' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg — South Africa' },
  { value: 'Africa/Maputo', label: 'Africa/Maputo — Mozambique' },
  { value: 'Africa/Harare', label: 'Africa/Harare — Zimbabwe' },
  { value: 'Africa/Lusaka', label: 'Africa/Lusaka — Zambia' },
  { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar_es_Salaam — Tanzania' },
  { value: 'Africa/Kampala', label: 'Africa/Kampala — Uganda' },
  { value: 'Africa/Kigali', label: 'Africa/Kigali — Rwanda' },
  { value: 'Africa/Bujumbura', label: 'Africa/Bujumbura — Burundi' },
  { value: 'Africa/Dakar', label: 'Africa/Dakar — Senegal' },
  { value: 'Africa/Abidjan', label: 'Africa/Abidjan — Côte d’Ivoire' },
  { value: 'Africa/Bamako', label: 'Africa/Bamako — Mali' },
  { value: 'Africa/Ouagadougou', label: 'Africa/Ouagadougou — Burkina Faso' },
  { value: 'Africa/Conakry', label: 'Africa/Conakry — Guinea' },
  { value: 'Africa/Freetown', label: 'Africa/Freetown — Sierra Leone' },
  { value: 'Africa/Monrovia', label: 'Africa/Monrovia — Liberia' },
  { value: 'Africa/Bangui', label: 'Africa/Bangui — Central African Republic' },
  { value: 'Africa/Brazzaville', label: 'Africa/Brazzaville — Congo' },
  { value: 'Africa/Kinshasa', label: 'Africa/Kinshasa — DR Congo' },
  { value: 'Africa/Libreville', label: 'Africa/Libreville — Gabon' },
  { value: 'Africa/Malabo', label: 'Africa/Malabo — Equatorial Guinea' },
  { value: 'Africa/Sao_Tome', label: 'Africa/Sao_Tome — São Tomé & Príncipe' },
  { value: 'Africa/Windhoek', label: 'Africa/Windhoek — Namibia' },
  { value: 'Africa/Gaborone', label: 'Africa/Gaborone — Botswana' },
  { value: 'Africa/Maseru', label: 'Africa/Maseru — Lesotho' },
  { value: 'Africa/Mbabane', label: 'Africa/Mbabane — Eswatini' },
  { value: 'Africa/Antananarivo', label: 'Africa/Antananarivo — Madagascar' },
  { value: 'Africa/Mauritius', label: 'Indian/Mauritius — Mauritius' },
  { value: 'Africa/Seychelles', label: 'Indian/Seychelles — Seychelles' },

  // North America
  { value: 'America/New_York', label: 'America/New_York — United States (Eastern)' },
  { value: 'America/Chicago', label: 'America/Chicago — United States (Central)' },
  { value: 'America/Denver', label: 'America/Denver — United States (Mountain)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles — United States (Pacific)' },
  { value: 'America/Anchorage', label: 'America/Anchorage — United States (Alaska)' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu — United States (Hawaii)' },
  { value: 'America/Toronto', label: 'America/Toronto — Canada (Eastern)' },
  { value: 'America/Vancouver', label: 'America/Vancouver — Canada (Pacific)' },
  { value: 'America/Edmonton', label: 'America/Edmonton — Canada (Mountain)' },
  { value: 'America/Winnipeg', label: 'America/Winnipeg — Canada (Central)' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City — Mexico' },
  { value: 'America/Tijuana', label: 'America/Tijuana — Mexico (Northwest)' },
  { value: 'America/Monterrey', label: 'America/Monterrey — Mexico (North)' },
  { value: 'America/Guatemala', label: 'America/Guatemala — Guatemala' },
  { value: 'America/Belize', label: 'America/Belize — Belize' },
  { value: 'America/El_Salvador', label: 'America/El_Salvador — El Salvador' },
  { value: 'America/Managua', label: 'America/Managua — Nicaragua' },
  { value: 'America/Costa_Rica', label: 'America/Costa_Rica — Costa Rica' },
  { value: 'America/Panama', label: 'America/Panama — Panama' },
  { value: 'America/Tegucigalpa', label: 'America/Tegucigalpa — Honduras' },

  // South America
  { value: 'America/Bogota', label: 'America/Bogota — Colombia' },
  { value: 'America/Lima', label: 'America/Lima — Peru' },
  { value: 'America/Quito', label: 'America/Quito — Ecuador' },
  { value: 'America/Guayaquil', label: 'America/Guayaquil — Ecuador (Galapagos)' },
  { value: 'America/Caracas', label: 'America/Caracas — Venezuela' },
  { value: 'America/Santiago', label: 'America/Santiago — Chile' },
  { value: 'America/Punta_Arenas', label: 'America/Punta_Arenas — Chile (South)' },
  { value: 'America/Easter', label: 'Pacific/Easter — Chile (Easter Island)' },
  { value: 'America/Buenos_Aires', label: 'America/Buenos_Aires — Argentina' },
  { value: 'America/Cordoba', label: 'America/Cordoba — Argentina (Central)' },
  { value: 'America/La_Paz', label: 'America/La_Paz — Bolivia' },
  { value: 'America/Asuncion', label: 'America/Asuncion — Paraguay' },
  { value: 'America/Montevideo', label: 'America/Montevideo — Uruguay' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo — Brazil (East)' },
  { value: 'America/Manaus', label: 'America/Manaus — Brazil (West)' },
  { value: 'America/Fortaleza', label: 'America/Fortaleza — Brazil (Northeast)' },
  { value: 'America/Recife', label: 'America/Recife — Brazil (East North)' },
  { value: 'America/Rio_Branco', label: 'America/Rio_Branco — Brazil (Acre)' },
  { value: 'America/Cuiaba', label: 'America/Cuiaba — Brazil (Central West)' },
  { value: 'America/Porto_Velho', label: 'America/Porto_Velho — Brazil (Amazon)' },
  { value: 'America/Georgetown', label: 'America/Guyana — Guyana' },
  { value: 'America/Paramaribo', label: 'America/Paramaribo — Suriname' },
  { value: 'America/Cayenne', label: 'America/Cayenne — French Guiana' },
  { value: 'America/Port_of_Spain', label: 'America/Port_of_Spain — Trinidad & Tobago' },
  { value: 'America/Aruba', label: 'America/Aruba — Aruba' },
  { value: 'America/Curacao', label: 'America/Curacao — Curaçao' },

  // Oceania / Pacific
  { value: 'Australia/Sydney', label: 'Australia/Sydney — Australia (East)' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne — Australia (Southeast)' },
  { value: 'Australia/Brisbane', label: 'Australia/Brisbane — Australia (Northeast)' },
  { value: 'Australia/Perth', label: 'Australia/Perth — Australia (West)' },
  { value: 'Australia/Adelaide', label: 'Australia/Adelaide — Australia (Central)' },
  { value: 'Australia/Darwin', label: 'Australia/Darwin — Australia (Central NT)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland — New Zealand' },
  { value: 'Pacific/Chatham', label: 'Pacific/Chatham — New Zealand (Chatham)' },
  { value: 'Pacific/Port_Moresby', label: 'Pacific/Port_Moresby — Papua New Guinea' },
  { value: 'Pacific/Guam', label: 'Pacific/Guam — Guam' },
  { value: 'Pacific/Saipan', label: 'Pacific/Saipan — Northern Mariana Islands' },
  { value: 'Pacific/Fiji', label: 'Pacific/Fiji — Fiji' },
  { value: 'Pacific/Noumea', label: 'Pacific/Noumea — New Caledonia' },
  { value: 'Pacific/Tarawa', label: 'Pacific/Tarawa — Kiribati' },
  { value: 'Pacific/Tahiti', label: 'Pacific/Tahiti — French Polynesia' },
  { value: 'Pacific/Apia', label: 'Pacific/Apia — Samoa' },
  { value: 'Pacific/Tongatapu', label: 'Pacific/Tongatapu — Tonga' },
  { value: 'Pacific/Pago_Pago', label: 'Pacific/Pago_Pago — American Samoa' },

  // Atlantic
  { value: 'Atlantic/Azores', label: 'Atlantic/Azores — Portugal (Azores)' },
  { value: 'Atlantic/Madeira', label: 'Atlantic/Madeira — Portugal (Madeira)' },
  { value: 'Atlantic/Canary', label: 'Atlantic/Canary — Spain (Canary Islands)' },
  { value: 'Atlantic/Reykjavik', label: 'Atlantic/Reykjavik — Iceland' },
  { value: 'Atlantic/Bermuda', label: 'Atlantic/Bermuda — Bermuda' },
  { value: 'Atlantic/Stanley', label: 'Atlantic/Stanley — Falkland Islands' },
  { value: 'Atlantic/South_Georgia', label: 'Atlantic/South_Georgia — South Georgia' },
]

export const DEFAULT_TIMEZONE = 'Asia/Manila'
