-- CODENTRA — neutralize the legacy sales-totals trigger and clean stray
-- cash movements on the REMOTE database.
--
-- The drawer balance is now derived entirely from transaction status in
-- computeShiftExpectedCash() (opening + completed-sale cash - refunded/voided
-- cash + cash_in - cash_out). The old update_shift_totals() trigger used to
-- mutate shift running totals AND insert refund_payout/void_payout cash
-- movements on every void/refund, which double-deducted the amount. Editing
-- migration 012 alone does not re-apply to an already-migrated DB, so this
-- migration replaces the trigger function with a no-op and deletes the stray
-- payout/denomination movements it left behind.

-- 1) Replace the trigger function with a no-op. Sales/void/refund no longer
--    touch shift totals or create cash movements here.
CREATE OR REPLACE FUNCTION update_shift_totals()
RETURNS TRIGGER AS $$
BEGIN
  -- Intentionally empty: drawer expected cash is derived from transaction
  -- status in the application layer (computeShiftExpectedCash), not from
  -- shift running totals or trigger-generated cash movements.
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2) Remove any stray cash movements created by the old trigger logic.
--    refund_payout / void_payout were generated on void/refund and would
--    otherwise keep double-deducting. denomination_adjustment is dead data
--    (no UI creates it). cash_sale is never generated by current code.
DELETE FROM cash_movements
WHERE kind IN ('refund_payout', 'void_payout', 'denomination_adjustment', 'cash_sale');
